version: '3.8'
services:
  webapp:
    env_file:
      - .env
    build: ./
    working_dir: /webapp
    volumes:
      - .:/webapp
    ports:
      - "3000:3000"

networks:
  default:
    external:
      name: fidecloud
